# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        PlanetExpress\UserBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        planet_express_db_provider:
            entity:
                class: PlanetExpress\UserBundle\Entity\User
                property: username

#        in_memory:
#            memory:
#                users:
#                    fry:  { password: frypass, roles: ['ROLE_USER'] }
#                    admin: { password: adminpass, roles: ['ROLE_ADMIN'] }

    firewalls:
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        login:
#            pattern: ^/demo/secured/login$
#            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: login_check
                login_path: login
            logout:
                path:   logout
                target: event_index

            anonymous: ~
            #http_basic:
            #realm: "Secured Demo Area"

#    access_control:
#    Putting security in the controller class instead
#        - { path: ^/new, roles: ROLE_USER }
#        - { path: ^/create, roles: ROLE_USER }
