<?php

namespace PlanetExpress\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function findOneByUsernameOrEmail($username)
    {
        return $this->createQueryBuilder('user')
            ->andWhere('user.username = :username OR user.email = :email')
            ->setParameters(['username' => $username, 'email' => $username])
            ->getQuery()
            ->getOneOrNullResult();
    }
    
}
